export type TPeopleTypes =
	| 'Gottheit'
	| 'Bergsteiger:in'
	| 'Archäolog:in'
	| 'Musiker:in'
	| 'Regisseur:in'
	| 'Sagengestalt'
	| 'Verleger:in'
	| 'rassistische Bezeichnung'
	| 'Biblische Figur'
	| 'Scharzenbach-Forscher:in'
	| 'Fotograf:in'
	| 'Künstler:in'
	| 'Schauspieler:in'
	| 'Autor:in'
	| 'Mitarbeiter:in Medium'
	| 'Historische Person (ohne persönliche Bekanntschaft)'
	| 'Bekannte:r'
	| 'Redakteur:in'
	| 'Freund:in'
	| 'Familienangehörige:r';
