export type TPlacesGroups =
	| 'Berg'
	| 'Bundesstaat oder Kanton'
	| 'Gebirge'
	| 'Gebäude'
	| 'Gewässer'
	| 'Gletscher'
	| 'Höhle'
	| 'Insel'
	| 'Land'
	| 'Militärische Anlage'
	| 'Monument'
	| 'Park'
	| 'Pass'
	| 'Region'
	| 'Ruine/Ausgrabung'
	| 'Siedlung'
	| 'Staudamm'
	| 'Strasse'
	| 'Wüste';
