export type TSmallformsGroups =
	| 'Typoskript'
	| 'Manuskript'
	| 'Feuilleton'
	| 'Rezension'
	| 'Beilage'
	| 'Fotoreportage'
	| 'Fotografie'
	| 'Zeitschriftenartikel'
	| 'Zeitungsartikel'
	| 'Sammelband-Beitrag'
	| 'Serie'
	| 'Sammelband'
	| 'Typoskript, Serie?'
	| 'Typoskript, Rezension'
	| 'Sonderbeilage';
